lab_1/urls.py
from django.urls import re_path
from .views import index
#url for app
urlpatterns = [
    re_path(r'^$', index, name='index'),
]

lab_2/urls.py
from django.urls import path
from .views import index

#url for app, add your URL Configuration

urlpatterns = [
#TODO Implement this
]

lab_4/urls.py
from django.urls import re_path
from . import views

urlpatterns = [
    re_path(r'^$', views.home),
    re_path(r'^feedback/$', views.feedback, name='feedback'),
    re_path(r'^add_activity/$', views.activity_add, name='add_activity'),
    re_path(r'^post_activity/$', views.activity_post, name='post_activity'),
    re_path(r'^list_activity/$', views.activity_list, name='list_activity'),
    re_path(r'^delete_all_activity/$', views.activity_delete_all, name='delete_all_activity')
]

praktikum/urls.py
from django.conf.urls import include
from django.urls import re_path
from django.contrib import admin


urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^lab-1/', include('lab_1.urls')),
    re_path(r'^lab-2/', include('lab_2.urls')),
    re_path(r'^lab-4/', include(('lab_4.urls', 'lab_4'), namespace='lab-4'))
]

lab_1/models.py
from django.db import models

# Create your models here.

lab_2/models.py
from django.db import models

# Create your models here.

lab_4/models.py
from django.db import models

# Create your models here.
class Activity(models.Model):
    date = models.DateField()
    time = models.TimeField()
    name = models.CharField(max_length=100)
    place = models.CharField(max_length=100, blank=True)
    category = models.CharField(max_length=30, blank=True)

    def __str__(self):
        return self.name
    

lab_4/forms.py
from django import forms
from .models import Activity

class Activity_Form(forms.ModelForm):
    class Meta:
        model = Activity
        fields = '__all__'
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),
            'time': forms.TimeInput(attrs={'type': 'time'}),
        }

lab_1/views.py
from django.shortcuts import render
from datetime import datetime, date

mhs_name = 'Muhammad Ridho Ananda'
curr_year = int(datetime.now().strftime("%Y"))
birth_date = date(1999, 4, 28) 
npm = 1706028682
college = 'Universitas Indonesia'
hobby = 'Reading / Watching'

def index(request):
    response = {'name': mhs_name, 
                'age': calculate_age(birth_date.year),
                'npm': npm,
                'college' : college,
                'hobby' : hobby,
                }
    return render(request, 'index_lab1.html', response)

def calculate_age(birth_year):
    return curr_year - birth_year if birth_year <= curr_year else 0

lab_2/views.py
from django.shortcuts import render
from lab_1.views import mhs_name, birth_date

#TODO Implement
#Create a content paragraph for your landing page:
landing_page_content = ''

def index(request):
    response = {'name': mhs_name, 'content': landing_page_content}
    return render(request, 'index_lab2.html', response)

lab_4/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import Activity
from .forms import Activity_Form

# Create your views here.
def home(request):
    return render(request, 'home.html')

def feedback(request):
    return render(request, 'feedback.html')

def activity_add(request):
    response = {}
    response['activity_form'] = Activity_Form
    return render(request, 'add_activity.html', response)

def activity_post(request):
    response = {}
    form = Activity_Form(request.POST or None)
    if (request.method == 'POST' and form.is_valid()):
        response['date'] = request.POST['date']
        response['time'] = request.POST['time']
        response['name'] = request.POST['name']
        response['place'] = request.POST['place']
        response['category'] = request.POST['category']
        activity = Activity(date=response['date'], time=response['time'], name=response['name'],
                            place=response['place'], category=response['category'])
        activity.save()
        return HttpResponseRedirect('/lab-4/list_activity')
    else:
        return HttpResponseRedirect('/lab-4/add_activity')

def activity_list(request):
    response = {}
    activity = Activity.objects.all()
    response['activity'] = activity
    return render(request, 'list_activity.html', response)

def activity_delete_all(request):
    Activity.objects.all().delete()
    return HttpResponseRedirect('/lab-4/list_activity')

lab_1/templates/index_lab1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>INI TITLE</title>
</head>
<body>
    <img src="https://media.licdn.com/dms/image/C5103AQH1_dFTPONWoQ/profile-displayphoto-shrink_200_200/0?e=1540425600&v=beta&t=566E-H3xkXFZUwyXgOn2o58IbAmoP9TXYI_H8mxNA98"</img>
    <article>Name : {{ name }}</article>
    <article>NPM : {{ npm }}</article>
    <article>Age : {{ age }}</article>
    <article>College : {{ college }}</article>
    <article>Hobby : {{ hobby }}</article>
    <article>Short description : Hello everyone! I am a student from Universitas Indonesia majoring Computer Science.
        I love to code and learn something new everyday!</article>
	
	<p> Here is a short description about my friends in front of and behind me </p>
		
	<img src="https://media.licdn.com/dms/image/C5603AQE5axwoQdxkrw/profile-displayphoto-shrink_200_200/0?e=1541635200&v=beta&t=p83ey2qe5Fi60depTRK4vgjNZpm2-aLeH5V_CChqVy0"></img>
	<article>Name : Alif</article>
    <article>NPM : 1406568721</article>
    <article>Age : 21</article>
    <article>College : Universitas Indonesia</article>
    <article>Hobby : Swimming</article>
    <article>Short description : A student from Faculty of Math & Science who is taking PPW class</article>
	
	<p> </p>
	
	<img src="https://ardycupu.files.wordpress.com/2012/03/tembok.jpg" width="200" length="200"></img>
	<article>Name : Tembok</article>
    <article>NPM : -</article>
    <article>Age : -</article>
    <article>College : Universitas Indonesia</article>
    <article>Hobby : Standing</article>
		
</body>		
</html>

lab_2/templates/description_lab2addon.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My Biodata</title>
</head>
<style>
    table, th, td {
        border: 1px solid black;
    }
    .subject{
        font-size: 20px;
        font-family: "Comic Sans MS";
        color: #6650ff;
    }
    .value{
        font-size: 20px;
        font-family: "Roboto", "Lucida Grande", Verdana, Arial, sans-serif;
        color: #ff102c;
    }
</style>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<body style="background-color: aqua">
    <h3 style="text-align: center">Hi all, This is my complete biodata</h3>
    <table align="center" style="text-align: center">
        {% for bio in bio_dict %}
            <tr>
                <td class="subject">{{ bio.subject }}</td>
                <td class="value">{{ bio.value }}</td>
            </tr>
        {% endfor %}
    </table>
    <br><br>
</body>

</html>

lab_2/templates/index_lab2.html
{% extends "base.html" %}
{% block content %}
<style>
    .center_screen {
        position: absolute;
        width: 500px;
        height: 50px;
        top: 50%;
        left: 50%;
        margin-left: -250px; /* margin is -0.5 * dimension */
        margin-top: -25px;
    }
</style>
<div class="center_screen">
    <p class="status" id="test">Hello, this is {{ name }}. {{ content }}.</p>
</div>
{% endblock %}

lab_4/templates/add_activity.html
{% extends 'index.html' %}
{% load static %}
{% block content %}

<div class="container-fluid text-center">
    <h2 style="margin-top:25px">Add Activity</h2>
    <section name="form">
        <form method="POST" action="{% url 'lab-4:post_activity' %}">
            {% csrf_token %}
            {% for i in activity_form %}
                <p>{{i.label_tag}} {{i}}</p>
            {% endfor %}
            <button type="submit" class="btn btn-default">Submit</button>
        </form>
    </section>
</div>

{% endblock %}

lab_4/templates/feedback.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
<div class="container-fluid text-center">    
  <div class="row content">
    <div class="col-sm-12 sidenav">
      <h2>Feedback</h2>
      <p class="short-paragraph">Do you have any comments about my website?
      <br> Please do not hesitate to send me a message.
      <br> Any kind of feedback would be really appreciated.
      </p>
    </div>
  </div>
</div>

{% endblock %}

lab_4/templates/home.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
<div class="container-fluid text-center">    
  <div id="home">
    <div class="row content">
      <div class="col-sm-2 sidenav">
        <img 
        id="my-image"
        src="https://media.licdn.com/dms/image/C5103AQH1_dFTPONWoQ/profile-displayphoto-shrink_200_200/0?e=1540425600&v=beta&t=566E-H3xkXFZUwyXgOn2o58IbAmoP9TXYI_H8mxNA98">
      </div>
      <div class="col-sm-10 text-left" id="description"> 
        <h2>Muhammad Ridho Ananda</h2>
        <p class="short-paragraph">Currently majoring Computer Science at Universitas Indonesia.
        <br>Interested at data science and competitive programming.
        <br>A student and a lifetime learner.
        </p>
      </div>
    </div>
  </div>
</div>

<div class="container-fluid text-center">
  <div id="resume">
    <p class="section-title">RESUME</p>  
    <div class="row content">
      <div class="col-sm-4 sidenav">
        <div class="card">
          <img class="card-img-top" data-src="holder.js/100x180/?text=Image cap">
          <div class="card-body">
            <h4 class="card-title">Education</h4>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item">SD YPS Singkole <br>(2005-2011)</li>
            <li class="list-group-item">SMP Pribadi Bandung <br>(2011-2014)</li>
            <li class="list-group-item">SMA Pribadi Bandung <br>(2014-2017)</li>
            <li class="list-group-item">Universitas Indonesia <br>(2017-now)</li>
          </ul>
        </div>
      </div>  
      <div class="col-sm-4 sidenav">
        <div class="card">
          <img class="card-img-top" data-src="holder.js/100x180/?text=Image cap">
          <div class="card-body">
            <h4 class="card-title">Work Experience</h4>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item">Software Engineer Internship at GDP Labs <br>
              (Jun 2017-Aug 2017)</li>
            <li class="list-group-item">Discrete Mathematics 1 Teaching Assistant <br>
              (Sep 2017-now)</li>
          </ul>
        </div>
      </div>
      <div class="col-sm-4 sidenav">
        <div class="card">
          <img class="card-img-top" data-src="holder.js/100x180/?text=Image cap">
          <div class="card-body">
            <h4 class="card-title">Projects</h4>
          </div>
          <ul class="list-group list-group-flush">
          </ul>
        </div>
      </div> 
    </div>
  </div>
</div>

<div class="container-fluid">
  <div id="skills">
    <p class="section-title">SKILLS</p>  
    <div class="row content">
      <div class="col-sm-12 sidenav">
        <div class="card-group">
          <div class="card" id="skills-card">
            <img class="card-img-top" data-src="holder.js/100x180/">
            <div class="card-body">
              <h4 class="card-title">Java</h4>
            </div>
          </div>
          <div class="card" id="skills-card">
            <img class="card-img-top" data-src="holder.js/100x180/">
            <div class="card-body">
              <h4 class="card-title">Python</h4>
            </div>
          </div>
          <div class="card" id="skills-card">
            <img class="card-img-top" data-src="holder.js/100x180/">
            <div class="card-body">
              <h4 class="card-title">Git</h4>
            </div>
          </div>
          <div class="card" id="skills-card">
            <img class="card-img-top" data-src="holder.js/100x180/">
            <div class="card-body">
              <h4 class="card-title">OOP</h4>
            </div>
          </div>
          <div class="card" id="skills-card">
            <img class="card-img-top" data-src="holder.js/100x180/">
            <div class="card-body">
              <h4 class="card-title">Machine Learning</h4>
            </div>
          </div>
          <div class="card" id="skills-card">
            <img class="card-img-top" data-src="holder.js/100x180/">
            <div class="card-body">
              <h4 class="card-title">Competitive Proramming</h4>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}  

lab_4/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <title>I Love CSS</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="stylesheet" href={% static 'styles.css' %}>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
</head>
<body>

<div class="content">
<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
  <a class="navbar-brand" href="#">Logo</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavId" aria-controls="collapsibleNavId"
    aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span></button>
  <div class="collapse navbar-collapse" id="collapsibleNavId">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <a class="nav-link" href="/lab-4/">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/lab-4/feedback/">Feedback</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/lab-4/add_activity/">Add Activity</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/lab-4/list_activity/">My List</a>
      </li>
    </ul>
  </div>
</nav>

{% block content %}
{% endblock %}

</div>

<footer class="container-fluid text-center">
  <div id="contact">
    <h2>CONTACT ME</h2>
    <div id="my-contact">
      <p>Phone  : 081241217966</p>
      <p>Email  : mridho2828@gmail.com</p>
      <p>Address : Jl. Haji Koja 58</p>
    </div>
  </div>
</footer>

</body>
</html>

lab_4/templates/list_activity.html
{% extends 'index.html' %}
{% load static %}
{% block content %}

<div class="container-fluid text-center">
    <p class="section-title">MY ACTIVITY LIST</p>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Tanggal</th>
            <th>Jam</th>
            <th>Nama Kegiatan</th>
            <th>Tempat</th>
            <th>Jenis</th>
        </tr>
        </thead>
        <tbody>
        {% for i in activity %}
            <tr>
                <td>{{ i.date }}</td>
                <td>{{ i.time }}</td>
                <td>{{ i.name }}</td>
                <td>{{ i.place }}</td>
                <td>{{ i.category }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <form action="{% url 'lab-4:delete_all_activity' %}" method="POST" style="margin-bottom:25px">
        {% csrf_token %}
        <input class="btn btn-default btn-danger" type="submit" value="Delete All"/>
    </form>
</div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My Biodata</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
</head>
<style>
    table, th, td {
        border: 1px solid black;
    }
    .subject{
        font-size: 20px;
        font-family: "Comic Sans MS";
        color: #6650ff;
    }
    .value{
        font-size: 20px;
        font-family: "Roboto", "Lucida Grande", Verdana, Arial, sans-serif;
        color: #ff102c;
    }
</style>
<body style="background-color: lightgray">
    <div class="container-fullwidth">
        <nav class="navbar navbar-default navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="/lab-2/">Home</a>
              </li>
              <li class="nav-item" >
                <a class="nav-link" href="/lab-2-addon/">About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/lab-3/">Diary</a>
              </li>
            </ul>
          </div>
        </nav>
    </div>
    {% block content %}
    {% endblock %}
</body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
{% block jquery %}
{% endblock %}
</html>

templates/description_lab2addon.html
{% extends "base.html" %}
{% block content %}
<h3 style="text-align: center">Hi all, This is my complete biodata</h3>
<table align="center" style="text-align: center">
    {% for bio in bio_dict %}
        <tr>
            <td class="subject">{{ bio.subject }}</td>
            <td class="value">{{ bio.value }}</td>
        </tr>
    {% endfor %}
</table>
<br><br>
{% endblock %}

templates/to_do_list.html
{% extends "base.html" %}
{% block content %}
<h3 style="text-align: center">Hai semua, berikut adalah Catatan Harianku</h3>
<br><br>
<div class="row">
    <div class="col-md-6 col-xs-6">
        <table align="center" style="text-align: center">
            <tr>
                <th>Tanggal</th>
                <th>Yang akan dikerjakan</th>
            </tr>
            {% for diary_data in diary_dict %}
                <tr>
                    <td class="date">{{ diary_data.date }}</td>
                    <td class="activity">{{ diary_data.activity }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
    <div class="col-md-6 col-xs-6">
        <form method="POST" action="add_activity/">
            {% csrf_token %}
            <table>
                <tr>
                    <td>
                        Tanggal
                    </td>
                    <td>
                        <input type="datetime-local" name="date" id="date" required="required"/>
                    </td>
                </tr>
                <tr>
                    <td>
                        Kegiatan
                    </td>
                    <td>
                        <input type="text" name="activity" id="activity" size="25"/>
                    </td>
                </tr>
            </table>
            <button type="submit" class="button btn-success">Submit</button>
        </form>
    </div>
</div>
{% endblock %}